### ISSUE TITLE
project scope?

### ISSUE THREAD

**Issue by belm0** [axiros/axblack#1]
what is the scope of this project?

would you consider a contribution for the following?:  An option to make black less brutally wasteful of vertical space.

**Comment by axgkl** [comment]
Hi,
the project is currently only intended to bridge the time period until they support single quotes, which is a must for us and which I'm sure they'll accept one day due to the increased [pressure](https://pypi.org/project/oitnb/) with increasing popularity => we can't invest much effort deviating yet more from the official version.   

> wasteful of vertical space.

Some internals reacted the same way. In a bigger project we handled it by setting the line length even to 100. Right now we are reasonably happy with it, so I recommend you do your own fork if line length is not helping you.
